version: '3'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: nextjs-app
    ports:
      - '8080:3000'
    volumes:
      - .:/home/node/app
    depends_on:
      - db
